In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [12]:
with tf.Graph().as_default():
    x = tf.constant(8, name='x_const')
    y = tf.constant(5, name='y_const')    
    z = tf.add(x, y)
    
    with tf.Session() as sess:
        rslt = z.eval()
        print(rslt)

13


In [65]:
g = tf.Graph()
with g.as_default():
    random = tf.get_variable('dice', initializer=tf.random_uniform((10,2), dtype=tf.int32, maxval=7, minval=1))
    slice_a = tf.slice(random, [0,0], [-1,1])
    slice_b = tf.slice(random, [0,1], [-1,1])
    summ = tf.add(slice_a, slice_b)
    array = tf.concat([random, summ], axis=1)
#     array = tf.concat((random, tf.add(random[:,[0]], random[:,[1]])), axis=1)
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
#         print(sess.run(summ))
        print(sess.run(array))        

[[1 1 2]
 [1 2 3]
 [3 4 7]
 [5 4 9]
 [3 4 7]
 [4 2 6]
 [2 4 6]
 [5 4 9]
 [2 2 4]
 [1 2 3]]
